### ISSUE TITLE
cannot find settings.lris_blue, settings.lris_red files when running ./pypit_test 

### ISSUE THREAD

**Issue by caiz12** [PYPIT/PYPIT#101]
I use python3.5, and retrieved and installed all the most updated packages on Github. 

When I run "./pypit_test lris" in test_suite, it says: 

"No such file or directory: 
[BUG]     :: There appears to be a bug on Line 514 of arload.py with error:
             [Errno 2] No such file or directory: '/Users/zhengcai/software/PYPIT/build/lib.macosx-10.5-x86_64-3.5/pypit/settings.lris_blue'
             ---> please contact the authors"

        I checked and found settings.* is actually in here: 

/Users/zhengcai/software/PYPIT/pypit/

        How can let PYPIT find this directory "/Users/zhengcai/software/PYPIT/pypit/" as default? 
 I already added the following lines into ~/.cshrc 

setenv TST_PYPIT /Users/zhengcai/software/PYPIT/test_suite/
setenv PYPIT /Users/zhengcai/software/PYPIT/pypit
setenv PYPIT_CALIBS /Users/zhengcai/software/PYPIT-development-suite/PYPIT_CALIBS

**Comment by profxj** [comment]
1.  What branch are you on?  Seems like you might be off the master
2.  Where in the docs did you find instructions to do

setenv TST_PYPIT /Users/zhengcai/software/PYPIT/test_suite/
setenv PYPIT /Users/zhengcai/software/PYPIT/pypit
setenv PYPIT_CALIBS /Users/zhengcai/software/PYPIT-development-suite/PYPIT_CALIBS

We need to remove that.

**Comment by caiz12** [comment]
Problem solved. Errors because I didn't follow PYPIT doc to install GSL using anaconda. After deleting my previous GSL and installing it using anaconda and updating proper .cshrc file, then problem solved.

**Comment by profxj** [comment]
Remember to close your issue when it is resolved.
