### ISSUE TITLE
index selection bug in arsort.match_science

### ISSUE THREAD

**Issue by adwasser** [PYPIT/PYPIT#103]
In `arsort.match_science`, the time difference is calculated between each frame and a target science frame (line 437).   This value should be less than that specified in `spect['fits']['calwin']`.  The next line gets the indices satisfying that criterion, but then we should set the indices of interest to `n[w]` rather than  the intersection of `n` (the indices corresponding to the frames) and `w` (the indices of `n` which match the time window).  The `time_window_fix` branch makes that switch, but someone should check this to make sure it makes sense.

**Comment by rcooke-ast** [comment]
Good catch, you are correct, because the time difference is only calculated on a subset of the frames. Please submit a PR and merge  :-)

**Comment by profxj** [comment]
Addressed by PR #104
