### ISSUE TITLE
xrange and range

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#109]
It appears that Python3's range is the same as Python2's xrange.
There is no equivalent of Python2's range in Python3.

To be Python3 compliant we should replace all xrange instances with range
and I leave it to @rcooke-ast  to decide whether to rename range as xrange throughout the package.

**Comment by rcooke-ast** [comment]
I hadn't realized the incompatibility issue... When xrange is used in a for loop, we can simply replace it with range without too much of a slow down (for small loops, which is true almost always). I don't think range is ever used in the code outside a for loop (that I recall), so I think we're compatible there.

**Comment by profxj** [comment]
Indeed.  My mistake.  Will begin the xrange -> range conversion (and many 
other things) in a python3 branch.

**Comment by rcooke-ast** [comment]
Addressed by PR #116

**Comment by rcooke-ast** [comment]
Addressed by PR #116
