### ISSUE TITLE
arload.load_headers is failing to recognize strings with spaces

### ISSUE THREAD

**Issue by adwasser** [PYPIT/PYPIT#111]
The line below replaces spaces with an empty string, and so any header entries with strings fail to be matched.

[https://github.com/PYPIT/PYPIT/commit/2718b76bc795ec008daf667315233e6f5152d402#diff-73e36695d52ea8945cfe778bacd5530fR578]

Is this addition necessary for the WHT settings? If not, the branch iss111 reverts the change.

**Comment by profxj** [comment]
It was necessary, but I can use a different approach.  
Can you give me an example of a failure case with this 'new' approach?  Thanks

**Comment by adwasser** [comment]
For LRIS blue there's a setting line `check 02.CCDGEOM e2v_(Marconi)_CCD44-82` which stores the string to check as `" e2v (Marconi) CCD44-82"`.  Replacing the spaces by an empty string will cause the header keyword check to fail, thus preventing PYPIT from matching any frames to the detector.

**Comment by adwasser** [comment]
Adding an underscore to the ISIS blue arm check should work with the previous version of arload.
