### ISSUE TITLE
arsort.sort_data can't deal with single string input for canbe

### ISSUE THREAD

**Issue by adwasser** [PYPIT/PYPIT#112]
See diff for [https://github.com/PYPIT/PYPIT/commit/f2918b22b8a91052e0f4e34dd49226cccba27ee8]

If `canbe` is a single string instead of a list of strings, the current version will attempt to loop through that string, .e.g, if canbe = 'pixflat', then cb = 'p'

**Comment by profxj** [comment]
I'm giving this one to Ryan. ;)

**Comment by rcooke-ast** [comment]
I've fixed this in the `armed` branch (PR is not imminent, but is coming). I'm not sure the `canbe` option is really used, anyway...
