### ISSUE TITLE
hdf5?

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#121]
I'm finding myself rather enamored with hdf5 files.  
Allow me to propose that we use them for I/O instead of FITS.
They would work especially well for the spec1d and spec2d outputs.

Thoughts?

**Comment by rcooke-ast** [comment]
I'm not against the idea (in fact, having used HDF5 files before, I'm rather for it). However, apart from the simulation community, I'm not sure many people using the pipeline would know how to interrogate HDF5 files (and would probably prefer fits files).

We could allow the user to choose which file format they prefer (with HDF5 as default)? The only "problem" with this, is that we would have to support the two different file formats...

**Comment by profxj** [comment]
good point about the issues you raise.  
Let me stew on them.  Before proceeding.

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/ <http://www.ucolick.org/~xavier/>
http://imps.ucolick.org/ <http://imps.ucolick.org/>
http://www.qpqsurvey.org/ <http://www.qpqsurvey.org/>
http://k1dm3.ucolick.org/ <http://k1dm3.ucolick.org/>
http://www.ucolick.org/~xavier/IDL/index.html <http://www.ucolick.org/~xavier/IDL/index.html>
https://github.com/profxj/xastropy <https://github.com/profxj/xastropy>

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by profxj** [comment]
I have started an hdf5 branch for 1D spectra
and am proceeding on it.

The current method will be renamed
save_1d_spectra -> save_1d_spectra_fits

**Comment by profxj** [comment]
Implemented in PR#132
