### ISSUE TITLE
assert the version of each dependency

### ISSUE THREAD

**Issue by rcooke-ast** [PYPIT/PYPIT#133]
For the flexure correction, we use `fill_value='extrapolate'`, but this is only new in version 0.17.0 of scipy. I couldn't identify how (or if) we currently assert the version of each required package, but we should implement this.

**Comment by adwasser** [comment]
I don't know if it's checked anywhere, but we could use the `distutils.version` implementation of version comparison, see [here](http://stackoverflow.com/a/6972866).

**Comment by adwasser** [comment]
#134 should address this.  I'm not sure what the minimum version requirements are for the other required packages, but that can easily be put into the `minimum_versions` dictionary in `archeck`.
