### ISSUE TITLE
Settings File or PYPIT file

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#154]
This is just a terminology query, but should we refer to the 
.pypit files as Settings Files (as is current) or a PYPIT file?

My main source of concern is that the code now generates
a .settings file, which is good but may easily be confused
as being what we now call a Settings File.

As such, I might advocate we use PYPIT file for .pypit.  Or
Reduction File. Or something.

**Comment by rcooke-ast** [comment]
I'm all for calling it a PYPIT file - that makes sense, since it's the name of the extension (e.g. a file ending in *.fits is called a "fits file").

**Comment by profxj** [comment]
And so it shall be so!
