### ISSUE TITLE
Trouble with run_pypit 

### ISSUE THREAD

**Issue by AlexaVillaume** [PYPIT/PYPIT#162]
Hope it's okay to post an install/using pypit problem here, instead of a development issue.

I'm trying to install PYPIT and while all the unit tests pass my "run_pypit" script isn't working. For context I'm running OS X Yosemite and installed pypit and all of it's dependencies in a conda environment running python 3.5.2. When I try to execute "run_pypit" I get the following error,

`Traceback (most recent call last):
  File "/Users/alexa/anaconda/envs/py35/bin/run_pypit", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/alexa/PYPIT/bin/run_pypit", line 12, in <module>
    import pypit.scripts.run_pypit as run_pypit
ImportError: No module named 'pypit.scripts'`

In my .bash_profile file I have the following environment variables,

`export GSL_PATH="/Users/alexa/anaconda/envs/py35"
`

Does anybody have experience with a problem of this type?

**Comment by profxj** [comment]
Here are a few things to consider:

1.  PYPIT is not ready for Python 3.5
It is getting there, but surely won't work for now.

2.  I assume you used (and ran successfully):
python setup.py install

3.  What do you see if you just do:

ipython
import pypit

**Comment by AlexaVillaume** [comment]
> PYPIT is not ready for Python 3.5
It is getting there, but surely won't work for now.

Ah, okay. In the listing of dependencies on the installation instructions is says python python 3.3 or later. What is the recommended version for PYPIT now? Python 3.3?

> I assume you used (and ran successfully):
python setup.py install

Correct.

> What do you see if you just do:

ipython
import pypit

PYPIT imports without an error.

**Comment by AlexaVillaume** [comment]
The issues seems to be in importing pypit.scripts, which raises an error ("ImportError: No module named scripts"). I don't know why this would be a problem since the scripts subdirectory has the __init__.py file in it. Any thoughts @profxj ?

The error that I'm getting now why I try "run_pypit" is, 

`Traceback (most recent call last):
  File "/Users/alexa/anaconda/bin/run_pypit", line 4, in <module>
    __import__('pkg_resources').run_script('pypit==0.6.dev0', 'run_pypit')
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/setuptools-26.1.1-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/setuptools-26.1.1-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/Users/alexa/anaconda/lib/python2.7/site-packages/pypit-0.6.dev0-py2.7-macosx-10.6-x86_64.egg/EGG-INFO/scripts/run_pypit", line 12, in <module>
    import pypit.scripts.run_pypit as run_pypit
ImportError: No module named scripts.run_pypit`

**Comment by profxj** [comment]
This appears to be a failure with 

python setup.py install

and how scripts are handled (by Anaconda?).  To be fixed...

**Comment by AlexaVillaume** [comment]
Hi X,

Do you think you could meet with me again about a problem I’m having with PYPIT? It’s regarding PYPIT not recognizing the trace frame even after I set a trace frame in the Spect block. If you’d like I can make an issue for it on GitHub.

Best,
Alexa

**Comment by profxj** [comment]
Resolve by PR#164
