### ISSUE TITLE
Version and Changes

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#189]
It is probably time to get more serious about version numbering
and maintaining a Changes file.

**Comment by profxj** [comment]
And it is nearly time to release v1.0

I propose March 13.  Should we make an astro-ph posting too??

**Comment by rcooke-ast** [comment]
Agreed that it is nearly time to release v1.0.

I had hoped that the echelle pipeline might be included in v1.0. It might also be a good idea to significantly reduce the number of "issues" before we release v1.0.

Is there a motivation to have v1.0 announced on March 13?

**Comment by profxj** [comment]
Updates to CHANGES.rst is now *required* with each PR.
