### ISSUE TITLE
QA as Notebooks

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#19]
It is possible to create ipython notebooks (.ipynb files) 
that one can then run (automatically or manually).

Consider having some/all QA in this mode.

**Comment by rcooke-ast** [comment]
Are we still considering this as an option? I think the current QA (possibly with the latest ginga enhancement in PR #170) should be sufficient. I'll leave it up to @profxj to close this issue.

**Comment by profxj** [comment]
Indeed, this was a pipe dream.  ;)
