### ISSUE TITLE
coadd_1dspec bug?

### ISSUE THREAD

**Issue by AlexaVillaume** [PYPIT/PYPIT#194]
In lines 44 and 46 of coadd_1dspec.py I find that the "+=" syntax breaks the file strings into individual characters which causes problems when trying to actually read in the files. I switched to the "files.append(ifl)" syntax and the script works fine. 

I happy to make a PR with this change but I wanted to check that it wasn't something just on my end.

**Comment by profxj** [comment]
you are right.  Have modified in the obj_info branch using

files += [ifl]
