### ISSUE TITLE
Rethink QA generation - do you have QA suggestions?

### ISSUE THREAD

**Issue by rcooke-ast** [PYPIT/PYPIT#206]
As per comments in PR #205, we should rethink the way QA are generated. Some suggestions are:

* Break the QA into multiple PDFs
* Keep all QA in a single PDF
* Write a QA GUI that allows the QA to be generated outside of the data reduction process

Please add additional thoughts/suggestions here!

**Comment by profxj** [comment]
Here is one:

- Generate individual PNG files in one folder per exposure
- Generate an html or Notebook with it that let's you see all in a Browser

People looking for help can then send us the folder (as a tarball) or 
individual PNGs.

**Comment by profxj** [comment]
I'm now pretty keen on my idea above and am
willing to try an implementation.

The HTML file will 'slurp' all PNGs in existence for 
a given exposure.  But, the creation dates will be
explicit (i.e. it should be clear where the code crashed, etc.)

**Comment by profxj** [comment]
Am trying this in branch qa_html_png

**Comment by profxj** [comment]
PNG approach now implemented.
