### ISSUE TITLE
Errors running PYPIT-development-suite

### ISSUE THREAD

**Issue by bomilvangjensen** [PYPIT/PYPIT#208]
When running "./pypit_test all" in PYPIT-development-suite, I get

[INFO]    :: Generating a mask of arc line saturation streaks
[BUG]     :: There appears to be a bug on Line 2535 of arcyarc.pyx with error:
             Out of bounds on buffer access (axis 1)
             ---> please contact the authors

in these 3 log files:
- lris_red_long_600_7500_d560.log3
- lris_blue_long_600_4000_d560.log3
- lris_blue_long_400_3400_d560.log3

and

[WARNING] :: Assuming unbinned, i.e.  1x1
[BUG]     :: There appears to be a bug on Line 500 of arsave.py with error:
             global name 'arutils' is not defined
             ---> please contact the authors

in this logfile:
- kast_blue_600_4310_d55.log3

I did not have those problems previously (using the code cloned on 07-Apr-2017).

**Comment by rcooke-ast** [comment]
This is probably the recent merge/PR that I submitted - I'll work on fixing these issues for the longslit data - thanks for mentioning them!  Stay tuned...

**Comment by profxj** [comment]
I am seeing the same thing:

(Pdb)         satmask = arcyarc.saturation_mask(frame, settings.spect[dnum]['saturation']*settings.spect[dnum]['nonlinear'])
*** IndexError: Out of bounds on buffer access (axis 1)

**Comment by rcooke-ast** [comment]
Addressed by PR #210
