### ISSUE TITLE
Cython files generating with cpython-36m-x86_64-linux-gnu.so under Python 3.6

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#211]
My build is generating Cython files with long extensions, e.g.
/home/xavier/local/Python/PYPIT/pypit/arcycomb.cpython-36m-x86_64-linux-gnu.so

This then leads to an ImportError.  And if I remove the excess extension, i.e.
copy to arcycomb.so  all is well.

If anyone can figure out how to control the output .so filename please
holler.  I can't...

This may be a hint (and it may not).
http://stackoverflow.com/questions/41558535/python-3-6-installation-and-lib64

**Comment by adwasser** [comment]
I see the same long extensions on build, but I don't get any import error either when running `run_pypit` or directly importing from a python shell.  Might be worth comparing the exact python distributions used.  I'm using python 3.6.1, installed with pyenv.

**Comment by profxj** [comment]
Odd..  
Only real change I've done is to turn off python2to3 in the setup.py file.

Anyhow, @adwasser if you had a few minutes to work on this with me
today, I'd be grateful.

**Comment by profxj** [comment]
Cannot repeat the Issue on my 2nd laptop but
it remains on one of them (ugh!).  Am closing for now.

**Comment by profxj** [comment]
Reinstalling pypit on laptop #2 fixed the issue.  Phew..
