### ISSUE TITLE
Slack Team

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#216]
Please sign on to this Slack team.  It isn't to circumvent 
github but to better coordinate code development.

https://join.slack.com/pypit/shared_invite/MTc5NDUzNjU5NzM0LTE0OTM4OTk5NzctMjAyMzUxYmY3ZA

I encourage you to use your github account name for this Slack Team

**Comment by bomilvangjensen** [comment]
I get:
This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available.

**Comment by rcooke-ast** [comment]
Hi Bo,

I've sent you an email invitation through Slack to join the PYPIT slack.

Cheers, Ryan.

**Comment by lwymarie** [comment]
Being largely a user rather than a developer, may I be invited?
