### ISSUE TITLE
How to set up the coadd yaml file 

### ISSUE THREAD

**Issue by AlexaVillaume** [PYPIT/PYPIT#222]
I'm trying to coadd three exposures, I'm running into issues and I think it might be because I'm misunderstanding how to setup the yaml file. Even after reading the documentation it's not clear to me what should be put in the 'object' key. 

Currently, my yaml file looks like this,

```
'filenames': [
              'spec1d_B225-G280_LRISb_2016Oct27T055241.fits',
              'spec1d_B225-G280_LRISb_2016Oct27T055724.fits',
              'spec1d_B225-G280_LRISb_2016Oct27T060210.fits'
              ]
'a': 
    'object': 'O290-S1592-D02-I0002'
    'outfile': 'b225_g280.hdf5'
```
The object ID was taken from the objinfo_B225-G280_LRISb_2016Oct27T055241.txt  file. However, that ID is slightly different for the other two files. The contents of the objinfo*.txt files are:

- objinfo_B225-G280_LRISb_2016Oct27T055241.txt 

```
|                 name | box_width | opt_fwhm |   s2n |
| O940-S8661-D01-I0002 |      1.35 |    1.215 |  0.40 |
| O290-S1592-D02-I0002 |     11.07 |    1.303 | 44.12 |
| O853-S1592-D02-I0002 |      4.46 |    1.850 |  0.96 |
| O215-S1592-D02-I0002 |      1.89 |    0.541 |  1.16 |
| O932-S1592-D02-I0002 |      2.97 |    1.225 |  0.32 |
| O710-S1592-D02-I0002 |      5.27 |    2.242 |  0.64 |
| O801-S1592-D02-I0002 |      1.49 |    5.291 |  0.35 |
| O041-S1592-D02-I0002 |      1.62 |    0.798 |  0.69 |
| O532-S1592-D02-I0002 |      1.49 |    2.396 |  0.12 |
| O598-S1592-D02-I0002 |      1.08 |    4.295 |  0.06 |
```

- objinfo_B225-G280_LRISb_2016Oct27T055724.txt

```
|                 name | box_width | opt_fwhm |   s2n |
| O457-S1592-D02-I0003 |     14.45 |    2.048 | 43.11 |
| O211-S1592-D02-I0003 |      1.62 |    0.841 |  0.50 |
| O874-S1592-D02-I0003 |      1.35 |    4.437 |  0.47 |
| O766-S1592-D02-I0003 |      1.49 |    4.881 |  0.13 |
| O633-S1592-D02-I0003 |      3.11 |    2.814 |  0.20 |

```

-  objinfo_B225-G280_LRISb_2016Oct27T060210.txt

```
|                 name | box_width | opt_fwhm |   s2n |
| O626-S1592-D02-I0004 |     10.80 |    3.163 | 43.58 |
| O932-S1592-D02-I0004 |      1.62 |    6.153 |  0.26 |
| O374-S1592-D02-I0004 |      1.49 |    1.161 |  0.48 |

```

When I do try to run the coadd code with the yaml file as it is above I get the following error, 
```

Traceback (most recent call last):
  File "/Users/alexa/anaconda/bin/pypit_coadd_1dspec", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/alexa/PYPIT/bin/pypit_coadd_1dspec", line 11, in <module>
    coadd_1dspec.main(args)
  File "/Users/alexa/PYPIT/pypit/scripts/coadd_1dspec.py", line 83, in main
    mtch_obj, idx = arspecobj.mtch_obj_to_objects(iobj, fdict[key])
TypeError: 'NoneType' object is not iterable
```

And it's because the object ID I put in the yaml file doesn't have a match for the available object IDs for two of the three exposures. So what is the correct way to set up the yaml file?

**Comment by tiffanyhsyu** [comment]
It looks to me you're setting up the yaml file correctly. The reason why you're not matching is because PYPIT has a hard coded "tolerance" for the object ID of 10 (and slit ID of 50). I'm assuming the objects you want to coadd are:

O290-S1592-D02-I0002
O457-S1592-D02-I0003
O626-S1592-D02-I0004

Usually, the multiple exposures I have on a single target have a similar object ID number, which I believe is just some number that indicates the location of your object's trace with respect to the entire slit trace, with 0 being the left side of your slit trace and 1000 being the right of your slit trace (or vice versa). But this isn't true in your case--457 and 626 are both > 10 away from 290.

This goes back to an issue that you might've raised (or I at least remember talking to you about it) about being able to specify the extension corresponding to each of the filenames that you want to coadd, so that object IDs aren't a problem. I don't remember if that ever got implemented?

**Comment by AlexaVillaume** [comment]
> This goes back to an issue that you might've raised (or I at least remember talking to you about it) about being able to specify the extension corresponding to each of the filenames that you want to coadd, so that object IDs aren't a problem. I don't remember if that ever got implemented?

Yes, Issue #195. In that @profxj said that it isn't necessary, specifying the object name should be sufficient. 

So should I just increase the tolerance in the code?

**Comment by tiffanyhsyu** [comment]
I think increasing the tolerance in the code will also pick up objects you *don't* want to coadd though, such as 

exposure 2: O211-S1592-D02-I0003
exposure 3: O374-S1592-D02-I0004

@profxj, can you clarify why being able to specify an extension isn't necessary?

**Comment by profxj** [comment]
If it isn't there already, I suggest someone make the tolerance an 
optional parameter that the user can change away from the default
(which is a pretty good one, IMO).

**Comment by AlexaVillaume** [comment]
@profxj: Yes, that is a good idea but I don't think that'll help in this case. As Tiffany pointed out the object IDs from exposure to exposure are so different (these exposures were dithered along the slit) that by extending the tolerance to include them would also include some of the erroneous extractions.

I think either being able to specify the extension of each exposure or having a way to toss out the junk extractions would work. Or do you have an alternative idea?

**Comment by rcooke-ast** [comment]
In general, I think coadding is a very difficult to automate. I agree that X's suggestion is a good first guess, but perhaps we should also find a way that allows the user to manually list the extracted spectra that should be coadded?

**Comment by profxj** [comment]
I am fine with a new approach using the YAML file that allows the 
user to input a list of object names.  I presume the required format
would be to follow the list of spec1d filenames.  @AlexaVillaume , 
feel free to make it so.
