### ISSUE TITLE
PYPIT-development-suite

### ISSUE THREAD

**Issue by marijana777** [PYPIT/PYPIT#225]
For kast-red, PYPIT-development-suite is not properly reducing data. For example, PYPIT-development-suite/REDUX_OUT/Kast_red/600_7500_d55/Science/ folder is empty, and some of the other files that were generated for kast-blue are missing for kast-red.

**Comment by profxj** [comment]
Raise this issue in this repo:
https://github.com/PYPIT/PYPIT-development-suite

**Comment by rcooke-ast** [comment]
Also, before raising an issue in the development suite, please check that the issue still exists with the recent merge of PR #15 (i.e. update your master branch of the development suite first). Thanks!
