### ISSUE TITLE
pypit_setup usage not updated

### ISSUE THREAD

**Issue by marijana777** [PYPIT/PYPIT#226]
1) pypit_setup -h 
usage: pypit_setup [-h] [-v VERBOSITY] [-d] [--extension EXTENSION]
                   [--pypit_file] [--redux_path REDUX_PATH] [-c]
                   files_root spectrograph

2) https://github.com/PYPIT/PYPIT/blob/master/doc/setup.rst and http://pypit.readthedocs.io/en/latest/setup.html#pypit-setup are not updated:
pypit_setup -pyp_file lris_blue_2016-Nov-23.pypit lris_blue

See issue 219.

**Comment by profxj** [comment]
I don't really understand this issue, but you are more than qualified
to fix it.  Do so.

**Comment by profxj** [comment]
@marijana777 -- Is this fixed?
If so, please close the Issue.

**Comment by profxj** [comment]
closing
