### ISSUE TITLE
pypit_setup classifies correctly and incorrectly

### ISSUE THREAD

**Issue by bpholden** [PYPIT/PYPIT#232]
When running pypit_setup for APF data, all of the files are classified correctly, but everything is also classified as a dark. 

The resulting .pypit file has:
# Spect
spect read
 pixelflat number 0
 arc number 1
 pinhole number 0
 trace number 0
 bias number 0
 standard number 0
spect end

which seems less than useful

**Comment by rcooke-ast** [comment]
Yes, I see this now, but it doesn't have an affect on the reduction if the user decides to subtract the bias level using the overscan region. We should nevertheless fix it by including the shutter keyword in the settings files.

**Comment by bpholden** [comment]
The issue I found was not regarding the bias. The Issue I found was that
nothing was correctly classified by setup. Without manual modification,
pypit would not run.

I found the correct keyword to use to classify darks from other frames. I
will try to modify the settings file and even archive the old ones when I
am done.

**Comment by profxj** [comment]
@bpholden -- Where do we stand on this?

**Comment by bpholden** [comment]
I spent a little time this weekend on this.

* I updated all of the required packages with conda
* I did a git pull

I get seven (7) errors with
% python setup.py test

six (6) are in test_arcoadd.py
one is in test_objfind.py

Blindly proceeding, I did the following:

% python pypit_test kast
Output directory exists.
Wrote ./kast_blue_2017-Nov-05.pypit
Wrote ./kast_blue_setup_A/kast_blue_setup_A.pypit
Finished running pypit on kast_blue_600_4310_d55 --- PASSED
[INFO]    :: Found 27 raw data frames
[INFO]    :: Input file loaded successfully


Running pypit on kast_blue_setup_A.pypit --- PASSED
[INFO]    :: Wrote: QA/J1217p3905_KASTb_2015May20T053818.97.html
[INFO]    :: Data reduction execution time: 3m 32.76s


Running pypit on kast_red_600_7500_d55.pypit --- FAILED
             ---> please contact the authors
[INFO]    :: Wrote: QA/MF_A.html



--- PYPIT DEVELOPMENT SUITE FAILED 1/3 TESTS ---

**Comment by rcooke-ast** [comment]
See Issue #279 - this is now a solved problem (it was a problem with the value of one of the settings keywords). I think this issue is unrelated to the APF problem.

**Comment by bpholden** [comment]
Hi Ryan

Just to be sure I understand, the seven errors in setup.py test are all
because of using the master branch? Because 279 only refers to the
development suite issue.

**Comment by rcooke-ast** [comment]
I suspect that the errors are not related to PYPIT - I think this is potentially a problem with linetools. I'm also getting a few other minor errors, but these should not affecting the frame types assigned to each frame. Thanks for checking!

**Comment by bpholden** [comment]
Thanks Ryan, I will ignore those and try to run the APF data through again.

**Comment by profxj** [comment]
outdated
