### ISSUE TITLE
Co-addition error

### ISSUE THREAD

**Issue by SunilSimha** [PYPIT/PYPIT#242]
I'm trying to co-add the spectra of two objects but I'm hitting a Pdb flag and continuation leads it to crash. I'm including the fits files and the .yaml file [here](https://www.dropbox.com/sh/a8bo04afwpm24u3/AADagyU1L5EwhgR6RV4l1WRga?dl=0). Here is the ouput from the terminal.
`
$pypit_coadd_1dspec qso_add_1d.yaml 
[INFO]    :: Loading extension 6 of spectrum /home/sunil/Desktop/WorkingDir/Keck/LRIS/2017mar19/Run_PYPIT/lris_red_setup_A/Science/spec1d_J092_J0927+2530_LRISr_2017Mar19T053722.fits
> /home/sunil/anaconda3/lib/python3.6/site-packages/linetools/spectra/xspectrum1d.py(230)__init__()
-> self.data[key][kk][gdsigval[-1]+1:].mask = True
(Pdb) c
Traceback (most recent call last):
  File "/home/sunil/anaconda3/bin/pypit_coadd_1dspec", line 11, in <module>
    coadd_1dspec.main(args)
  File "/home/sunil/anaconda3/lib/python3.6/site-packages/pypit/scripts/coadd_1dspec.py", line 105, in main
    spectra = arcoadd.load_spec(gdfiles, iextensions=extensions, extract=ex_value, flux=flux_value)
  File "/home/sunil/anaconda3/lib/python3.6/site-packages/pypit/arcoadd.py", line 504, in load_spec
    spectrum = arload.load_1dspec(fname, exten=extensions[ii], extract=extract, flux=flux)
  File "/home/sunil/anaconda3/lib/python3.6/site-packages/pypit/arload.py", line 408, in load_1dspec
    spec = XSpectrum1D.from_file(fname, exten=exten, **rsp_kwargs)
  File "/home/sunil/anaconda3/lib/python3.6/site-packages/linetools/spectra/xspectrum1d.py", line 67, in from_file
    slf = tio.readspec(ifile, **kwargs)
  File "/home/sunil/anaconda3/lib/python3.6/site-packages/linetools/spectra/io.py", line 116, in readspec
    xspec1d = parse_FITS_binary_table(hdulist, exten=exten, **kwargs)
  File "/home/sunil/anaconda3/lib/python3.6/site-packages/linetools/spectra/io.py", line 567, in parse_FITS_binary_table
    xspec1d = XSpectrum1D.from_tuple((give_wv_units(wave), fx, sig, co), **kwargs)
  File "/home/sunil/anaconda3/lib/python3.6/site-packages/linetools/spectra/xspectrum1d.py", line 145, in from_tuple
    spec = cls(iwave, iflux, sig=ltuple[2], co=ltuple[3], units=dict(wave=wv_unit, flux=fx_unit), **kwargs)
  File "/home/sunil/anaconda3/lib/python3.6/site-packages/linetools/spectra/xspectrum1d.py", line 230, in __init__
    self.data[key][kk][gdsigval[-1]+1:].mask = True
IndexError: index -1 is out of bounds for axis 0 with size 0
`

**Comment by tiffanyhsyu** [comment]
PYPIT's coadder defaults to coadding the optimal extraction of your spectrum instead of the boxcar extraction. For your two attached spectra, there is no successful optimal extraction---the optimal flux array is just NaNs (I figured this by looking at spec1[6].data['opt_flam'] and spec2[7].data['opt_flam']). Anyway, this is why the coadder is crashing. I think a reason why the optimal extraction doesn't get successfully saved is if PYPIT isn't able to get a good fit for the spatial profile of the object (but correct me if I'm wrong!). Long story short, you can coadd the boxcar extraction, which *does* exist, by adding the following line to your .yaml file: 'extract': 'box'

I was able to get a coadded spectrum this way, but let me know if you run into any problems!

**Comment by profxj** [comment]
Well spotted, @tiffanyhsyu 
 
@SunilSimha -- your penance is to add something to the
coaddition code to identify this 'problem' and notify the user.  :)

We can discuss how.

**Comment by SunilSimha** [comment]
Sure thing! How can I help?

**Comment by SunilSimha** [comment]
The error persists even after adding the line. I'm writing it this way:
`
'filenames': ['spec1d_J092_J0927+2530_LRISr_2017Mar19T053722.fits', 'spec1d_J092_J0927+2530_LRISr_2017Mar19T054501.fits']
'a':
  'object': ['O191-S1385-D02-I0036', 'O191-S1385-D02-I0037']
  'outfile': 'J092_qso.hdf5'
  'extract': 'box'
`
Is there an error in the syntax?

**Comment by tiffanyhsyu** [comment]
I can't tell exactly from the way it's showing up here, but it looks like 'extract' might be under the heading 'a'. If that's the case, it shouldn't be--it should be on the same level as 'filenames'. Does that help?

**Comment by SunilSimha** [comment]
Yes, that helps. Thanks!

**Comment by SunilSimha** [comment]
@profxj , Here's what I came up with. This snippet is an ammendment to coadd_1dspec.py at line 104 (master branch).

    elif len(mtch_obj) == 1:
        #Check if optimal extraction is present in all  objects. If not, warn the user and set ex_value to 'box'.
        hdulist = fits.open(fkey)
        obj_opt_flam = hdulist[mtch_obj[0]].data['OPT_FLAM']
        if any(isnan(obj_opt_flam)):
                msgs.warn("Object {:s} in file {:s} doesn't have an optimal extraction. Boxcar will be used instead.".format(mtch_obj[0],fkey))
                ex_value = 'box'
        gdfiles.append(fkey)
        gdobj += mtch_obj
        extensions.append(idx[0]+1)
