### ISSUE TITLE
Specification of the overscan and data regions

### ISSUE THREAD

**Issue by bomilvangjensen** [PYPIT/PYPIT#260]
If I'm not mistaken, the the overscan and data regions in the settings file have to be specified in a "Python way" and not in the probably more familiar "IRAF way", and this could be documented better, and possibly be changed. One example is settings.keck_hires which says:

  det01 datasec01 [0:2048,6:1030]       # Either the data sections or the header keyword where the valid data sections can be obtained

The test data file hires3018.fits has this in the header:

  NAXIS1  =                 1070 / length of data axis 1
  NAXIS2  =                 2048 / length of data axis 2
  DATASEC = '[7:1030,1:2048]'    / NOAO/IRAF data section

It seems that to go from the IRAF style ([7:1030,1:2048]) to the Python style ([0:2048,6:1030]) one has to switch x and y, and subtract one from the lower x and y limit (but not the upper one).

It would be helpful if the comments on the settings file indicated the format, and also indicated if this format also pertained to the header keyword if that were given. And it would be nice with some kind of option to use the IRAF style, which is likely what would be found in a header keyword. Not a high priority issue, of course.

**Comment by rcooke-ast** [comment]
Bo, you are exactly right. Sorry that this wasn't clear! I think you're right that this would be a useful addition to PYPIT, and I'll aim to implement this feature during the coming week.

I suppose it makes the most sense to require the IRAF format as input in the settings file (or a header keyword can be given), and then the switch is made to a python format.

I'll also update the docs to mention that this is the case. Stay tuned!

**Comment by rcooke-ast** [comment]
This is implemented in the branch `datasec`, which will be submitted soon for a PR.

**Comment by rcooke-ast** [comment]
Addressed by PR #284
