### ISSUE TITLE
Python 3 dependency in current master branch?

### ISSUE THREAD

**Issue by AlexaVillaume** [PYPIT/PYPIT#267]
I'm updating to the latest versions of pypit/arclines/linetools. I'm getting an error in the pypit test suite on the "FileExistsError" exception that's raised on line 47 of test_arflux.py. This is in an exception that only exists in Python 3 not Python 2.7. Does this mean that pypit now works for python 3 and we should make the switch? I remember that a few months ago not everything was quite compatible with Python 3 so I wanted to check before I made the switch.

**Comment by profxj** [comment]
Indeed, I have been using PYPIT with Python 3 for months now and
installation notes also indicate this:

http://pypit.readthedocs.io/en/latest/installing.html

Go forth and enjoy.
