### ISSUE TITLE
Non-linear wavelength offsets on LRISb

### ISSUE THREAD

**Issue by AlexaVillaume** [PYPIT/PYPIT#268]
Hi everyone, 

I'm having an issue with my wavelength solution on data for the 300/5000 LRIS grism. 

Here is a comparison of the reduced data (black) compared to a model (red). You can see that there are non-linear offsets in the wavelength between the model and data,

![screen shot 2017-10-16 at 1 36 36 pm](https://user-images.githubusercontent.com/5116488/31634062-1025478e-b277-11e7-858f-1d6bbbd3d19b.png)

The QA files for the wavelength solution do not look so bad to me compared to the examples in the documentation. I'm not sure what the origin of this problem is and I'm hoping someone might have some experience with similar issues. 

![arc_pca_a_01_aa_00](https://user-images.githubusercontent.com/5116488/31634249-b4778216-b277-11e7-91c6-3f4602f04e43.png)
![arc_pca_a_02_aa_00](https://user-images.githubusercontent.com/5116488/31634250-b48a54ae-b277-11e7-8f6e-efbfb8a6d18c.png)

![arc_1dfit_a_01_aa](https://user-images.githubusercontent.com/5116488/31634192-75ca1e5c-b277-11e7-9c70-915feca34fc7.png)
![arc_1dfit_a_02_aa](https://user-images.githubusercontent.com/5116488/31634193-75e8893c-b277-11e7-8e8f-de2136deabef.png)

I'm using the arclines method to get the wavelength solution.

**Comment by tiffanyhsyu** [comment]
This may be just one of a few problems that are going on here, but that wavelength calibration looks non ideal to me -- it's extrapolating and curving downwards towards the bluer end. I see a few (faint) lines blue-ward of the Hg 3651.12 line and I think having those lines identified and used in the wavelength calibration might help. I've attached an example QA file from my LRISb (600 grism) with similar faint lines, if that's useful at all.

![arc_1dfit_a_02_aa](https://user-images.githubusercontent.com/12650633/31635042-59207028-b27a-11e7-99ca-8243ffc51908.png)

**Comment by AlexaVillaume** [comment]
Are the blue lines getting rejected because they are so faint?

**Comment by AlexaVillaume** [comment]
I've been tooling around with the values in arcparam dict, trying to loosen the criteria so that the more lines are auto-IDd. Here is how I'm defining the arcparam dict for the 300/5000 grism, 

>             arcparam['n_first'] = 3
>             arcparam['wv_cen'] = 4500.
>             arcparam['disp'] = 1.43
>             arcparam['wvmnx'] = [1600, 7450]
>             arcparam['min_ampl'] = 100
>             arcparam['b1']= 2.72694493e-04
>             arcparam['b2']= -5.30717321e-09
>             arcparam['match_toler'] = 6
>             arcparam['Nstrong'] = 25
> 
> 

As you can see if my QA plot below I do ID more of the bluer lines but now I'm losing some of the stronger middle lines and the fit is way worse. Does anyone have a better sense of how I might be able to change these values to get a better wavelength solution?

![image](https://user-images.githubusercontent.com/5116488/31694437-263e3dae-b359-11e7-8dc2-e841da3f3258.png)

**Comment by rcooke-ast** [comment]
Hi Alexa,

Just to try something different, you could check out the `detect_lines_fix` branch, which I was working on a while ago (use the original parameters, though, in the arcparam dict). The problem to me seems to be that the solution is allowed to deviate too much from linear. It does appear to be getting most of the IDs correct though.

This solution may not work, because the development suite doesn't pass (only LRISr fails, though), which is why I haven't done a PR yet. But, let me know if this helps to solve your problem.

**Comment by AlexaVillaume** [comment]
A small update on this issue: 

I took test arc exposures on Keck yesterday of the individual lamps (my arc spectra use Hg, Cd, and Zn). I'm attaching a figure comparing the arc spectra for the individual lamps with the arc spectrum that I'm trying to use to reduce my data. As you can see, the forest of lines around 3000-3500 appears to be erroneous. Which is a big problem! Luckily, having exposures of the individual lamps has made it much easier to identify the lines. 

![arc_examine](https://user-images.githubusercontent.com/5116488/32301858-ed40d28a-bf1c-11e7-90b9-1b5bb66c63cc.png)

**Comment by rcooke-ast** [comment]
Can you use your new spectra to calibrate the wavelength (the flexure correction will correct any offset anyway).

By the way, you might be interested to [read this](https://www2.keck.hawaii.edu/inst/lris/arc_calibrations.html) about LRIS (particularly at the bottom of the page, with "notes on wavelength calibrations in the blue").

**Comment by AlexaVillaume** [comment]
> Can you use your new spectra to calibrate the wavelength (the flexure correction will correct any offset anyway)?

Yes. I re-ran the reduction with the new arc spectra and the wavelength solution looks much improved (see data/model comparison plots below). Note, that I had to increase the maximum allowed flexure to 100.

<img width="579" alt="screen shot 2017-11-02 at 12 10 10 pm" src="https://user-images.githubusercontent.com/5116488/32345250-e36a8b7a-bfc6-11e7-82a4-e90f38d21187.png">
<img width="582" alt="screen shot 2017-11-02 at 12 10 16 pm" src="https://user-images.githubusercontent.com/5116488/32345253-e54d19d0-bfc6-11e7-9ff2-c107f4f414f7.png">
<img width="576" alt="screen shot 2017-11-02 at 12 10 26 pm" src="https://user-images.githubusercontent.com/5116488/32345258-e8e8ad2a-bfc6-11e7-8398-4eb4e3c08aa1.png">

Here's the QA file for the arc spectrum -

![image](https://user-images.githubusercontent.com/5116488/32345367-309398c4-bfc7-11e7-8a55-930bc061af1c.png)

However, the sky subtraction is still not as good as I'd like it to be, see,

![image](https://user-images.githubusercontent.com/5116488/32345429-5d63c388-bfc7-11e7-89d0-73fef66474a4.png)

I wonder if this is symptomatic of the large flexure correction needed?

**Comment by rcooke-ast** [comment]
This does look much better. The large flexure correction could be explained if the exact same setup was not used. 100 pixels is large for a flexure correction (which should be a few pixels). So, I dare say that your setup may have been slightly different.

**Comment by AlexaVillaume** [comment]
> This does look much better. The large flexure correction could be explained if the exact same setup was not used. 100 pixels is large for a flexure correction (which should be a few pixels). So, I dare say that your setup may have been slightly different.

LRIS wasn't on the telescope when I took these new arcs. @profxj  said that would cause the instrument to be at maximum flexure.

**Comment by AlexaVillaume** [comment]
Thanks for you help everyone! I'm going to go ahead and close this issue.
