### ISSUE TITLE
Code flow

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#281]
Greetings Team,

Please check this out:

https://github.com/PYPIT/PYPIT/blob/setup_flow/doc/flow.rst

and offer advice on how to improve it.  I'll also be consulting
with a professional or two.

**Comment by profxj** [comment]
May use this:

http://pycallgraph.slowchop.com/en/master/

**Comment by bomilvangjensen** [comment]
I think some kind of code diagram/flowchart would be a great (and non-trivial) idea. I could think of several products:
- A list of the different *.py files and the functions they each contain, and a list of the executable scripts (e.g. pypit_setup and run_pypit) and how they relate to the Python code
- A graph of what functions call what functions (this may be what the The Python Call Graph module you link to does, it looks interesting!)
- Something that (also) illustrates what input files (both data files and the settings files) and output files are used and where they enter in the code flow

Your
https://github.com/PYPIT/PYPIT/blob/setup_flow/doc/flow.rst
list is hard for me to understand. It's not clear what the different entities are: *.py file names without the .py, function names, or something 3rd (like "spect", which may be "arparse.get_spect_class"). It's also not clear what the lines between the different entities mean. And from the UI perspective I would say that pypit_setup and run_pypit (the two executable scripts invoked from the UNIX shell) should be on the same level, but maybe they don't appear in your list.

**Comment by bpholden** [comment]
I would find something like this very useful. I often spend a lot of time
reading code to determine the flow, so working out ahead of time which
modules are called and what objects are passed around would be very helpful
in understanding the software.

The key thing that seems to be missing for me in the list of calls in the
example is what objects are being passed, beyond those specific to the
class. Because there are few cases where objects are listed, is this just
because most of the functions are that self-contained?

**Comment by tiffanyhsyu** [comment]
I agree with @bomilvangjensen that it'd be useful to include the *.py files when creating the flow for the data reduction process. I would be ok with not listing each of the functions they contain, but it'd be helpful to know when they are called and to do what part of the data reduction, and how one can check that step of the data reduction. I think this is similar to @bomilvangjensen's third bullet point -- in addition to knowing what input and output files are used, it might be useful to know what output files are being generated too. For example, after ararc.py, the results of the wavelength calibration can be found in the 'MF_A.html' file, in the sections with Arc_*.

**Comment by rcooke-ast** [comment]
Thanks for your patience while I mulled this over... I might be missing the point, but perhaps the following idea would clarify some of the issues raised by the folks above.

I have thought of an idea (maybe similar to what X already has in mind). I'm happy to discuss this further on Skype, if you think it would be useful.

I think we might see some benefit if we restructure the code a little. I quite like what we've done with the settings files (i.e. have a base of defaults, that subsequently get overwritten at higher levels). This way, if we change one default, we don't need to change every settings file. I think it would be helpful to do the same with the code. I propose that we sort the files into three groups:

**Driver routines** - _these files determine how PYPIT should be run, and include miscellaneous utility functions. Most people would not be interested in these scripts._
- pypit.py
- ginga.py
- pyputils.py
- arparse.py
- ... and others

**Reduction Recipes** - _these files determine the order of the reduction operations that need to be performed. Users may be interested in these files, if they wish to know the order of the data reduction._
- baseReduce.py, which would include the arsciexp.ScienceExposure class and the armbase.py routines.
- armlsd.py, which would include a class called ARMLSD that inherits the methods in baseReduce i.e. `class ARMLSD(baseReduce.ScienceExposure)`. The current content of armlsd.ARMLSD would then go into a function within the class called something like `armlsd.ARMLSD.reduce(self)`. By doing this, all of the current `slf` would just become `self`. As I describe below, _all_ references to `self` will be restricted to this file. Also, if we can simply overwrite one of the base methods if, for example, the flat-fielding needed a different recipe from ARMLSD and ARMED.
- armed.py, which would include a class called ARMED that inherits the methods in baseReduce, as above.
- I also propose that we create a new file (or rename armlsd.py) to be inclusive of multislit reduction. How about the name: ARMS (Automatic Reduction of Multislit Spectra)?

**(modularized) Reduction Algorithms** - _these files are the algorithms that are used to reduce the data. In all cases, we should not be passing an instance of the ScienceExposure class to any of the functions in these files. We should be passing all of the variables to these functions individually. That way, if someone wants to use one of the algorithms that we have written for something outside of PYPIT, they just need to pass in the appropriate variables, and not an instance of the ScienceExposure class._
- almost all of the files currently labelled `ar*.py`

I think we will still benefit from having several global variables defined (e.g. `settings`), and I'm not sure how best to get around this in the modularized reduction algorithms.

I also propose that we start using the status variable to indicate potential problems with the reduction (for example, if the residuals of the wavelength calibration is higher than desirable). This will allow us to run the development suite and check that the status returned is 0 (i.e. no problems). At the moment, the development suite can pass even if the data are not reduced sufficiently well (e.g. a poor wavelength calibration). I propose that we make `status` a list, and append any critical warnings to this list. This would require us to write a new file, called `arstatus.py` for lack of a better name, which will include defined ID numbers for several potential problems that we might like to flag during the development suite testing (e.g. 0:no problems, 1:poor wavelength calibration, 2:poor tracing, 3:high residuals in tilts). The status that is then returned by `armlsd.ARMLSD` will then be a list, something like: [1, 3] that lists all of the potential problems. If this list is empty, we know that the reduction has completed to our satisfaction. If it's not empty, we can caution the user at the end of the reduction for QA that they may wish to look more carefully at. We can also use a non-empty list to confirm that the development suite passes to our satisfaction.

**Comment by lucarizzi** [comment]
I like @rcooke-ast idea. The division in Driver/Recipes/Primitives is likely to be the base of any future code refactoring that might go into adopting a common pipeline infrastructure. The new version of ORACDR (originated at Joint Astronomy Centre) and ported to Python by Gemini as presented at the recent ADASS goes along these lines and it is going to be one the models that we look at.

**Comment by profxj** [comment]
Ok, this is all good input and good ideas.
Some of it, however, might require a lot of work (more than
I was willing to put in at the moment).

So, I think I am going to proceed to enhance what I've 
started (others are encouraged to help as well) and 
move on to generate it for the run_pypit script.

**Comment by profxj** [comment]
closing
