### ISSUE TITLE
Problem with bspline knot

### ISSUE THREAD

**Issue by AlexaVillaume** [PYPIT/PYPIT#283]
I hit a stop in the code because an issue with the bspline knots. Here's the relevant log information that directly proceeds the stop -- 

> [INFO]    :: Using mkoextinct.dat for extinction corrections.
> [INFO]    :: Using standard star FEIGE110
> [INFO]    :: Loading standard star file: /Users/alexawork/PYPIT/pypit//data/standards/calspec/feige110_005.fits.gz
> [INFO]    :: Fluxes are flambda, normalized to 1e-17
> [INFO]    :: Masking edges
> [WARNING] :: Should pull resolution from arc line analysis
> [INFO]    :: Masking Balmer
> [INFO]    :: Masking Telluric
> [INFO]    :: Masking Below the atmospheric cutoff
> [WARNING] :: Problem in the bspline knot

I did some tests and the problem is that the `x[gd]` and  `y[gd]` on line 106 of `arutils.py` aren't ordered from smallest to largest. It'd be pretty easy to add a check and sort the arrays as need be but I wanted to check if this is symptomatic of another issue first.

**Comment by rcooke-ast** [comment]
Hi Alexa - just a few questions to help diagnose the issue. What instrument data are you reducing? What do the QA look like (particularly the edge trace, tilt trace and wavelength solution)? Also, just to clarify, `y[gd]` doesn't need to be ordered from smallest to largest, only `x[gd]` does. Can you confirm that x[gd] is ordered from smallest to largest (I think it should already be a sorted array).

Thanks!  Ryan.

**Comment by profxj** [comment]
I'll chime in that this might happen if the standard star 
doesn't cover the spectrum input at certain wavelengths
but probably not.

More likely is that it is related to the masking of features..

**Comment by AlexaVillaume** [comment]
> I'll chime in that this might happen if the standard star
doesn't cover the spectrum input at certain wavelengths
but probably not.

Is this because PYPIT is using a standard spectrum from `data/standards/calspec`? Because I observed Fiege 110 with the same instrumental set up. Is there a way I can use my own standard spectrum in the reduction?

> Hi Alexa - just a few questions to help diagnose the issue. What instrument data are you reducing?

Apologies for not providing that in my original question. This is on LRISb for the 300/5000 grism. 

>  What do the QA look like (particularly the edge trace, tilt trace and wavelength solution)? Also, just to clarify, y[gd] doesn't need to be ordered from smallest to largest, only x[gd] does. Can you confirm that x[gd] is ordered from smallest to largest (I think it should already be a sorted array).

I'll have to get this to you once I get back on campus.

**Comment by tiffanyhsyu** [comment]
I'll also chime in that I've had this issue before and resolved it by increasing the bspline knot spacing. In my case, there was not always data between the x[gd] knots, which I think has to do with what X mentioned -- the masking of features. I believe the line to add to the .pypit file to change knot spacing had something like 'everyn' in it. I'm not sure that you're crashing due to the same issue though!

> Is this because PYPIT is using a standard spectrum from data/standards/calspec? Because I observed Fiege 110 with the same instrumental set up. Is there a way I can use my own standard spectrum in the reduction?

PYPIT should be using both your observation of Feige 110 [in units of counts] and the data/standards/calspec version of Feige 110 [flamda] to create a sensitivity function to flux your science observations. I think it's possible to run into a problem with bspline knots too if your standard star observation is taken with a setup that goes beyond the wavelength range of the data/standards/calspec version of your standard.

**Comment by AlexaVillaume** [comment]
Hi everybody,  

Thanks again for all your comments. Looking at the QA files it seems like this issue was another manifestation of my wavelength solution problems. I'm going to close this issue because it isn't an issue with the bspline interpolation. I did make an update to the fluxing documentation, both it's content and making it more accessible in the PYPIT documentation. I just created a PR for that.

**Comment by rcooke-ast** [comment]
Hi Alexa - For the record, you might like to try the new wavelength calibration solution (currently in PR status). Perhaps it will help your problem?

**Comment by AlexaVillaume** [comment]
Hi Ryan - Yes, I've been following that PR. I was going to wait until it got merged into master just so I'm not potentially introducing any more issues into my reduction.

**Comment by rcooke-ast** [comment]
Very wise  :-)

**Comment by lwymarie** [comment]
I still have the same problem. For Kast red 830/8460 grating. 
I don't see an active PR on wavelength calibration solution. If it's merged already, should the fix be in my version of PYPIT?
Tried setting reduce skysub everyn to 40 and 80 and didn't solve the issue.

**Comment by tiffanyhsyu** [comment]
I think for the 830/8460 grating, the bspline knot problem might be due to your spectrum going to redder wavelengths than PYPIT is currently equipped for...

I would check PYPIT's archived version of your standard -- do your observations go redder than the archived version?

**Comment by lwymarie** [comment]
Thanks for the prompt reply! I did check wavelength coverage. bd_33d2642_fos_003.fits.gz covers past 9000 angstroms, while my grating tilt results in wavelengths shortward of that.
