### ISSUE TITLE
Test failures after latest merges

### ISSUE THREAD

**Issue by AlexaVillaume** [PYPIT/PYPIT#286]
After PR #24 was merged in arclines (Fully automated wavelength calibration) I updated both PYPIT and arclines. When I ran the PYPIT unit tests I got the following failure,

```

=============================================== FAILURES ================================================
______________________________________________ test_npeaks ______________________________________________

    def test_npeaks():
        """ Test on find_nminima
        """
        # Read trace example
        tbl = Table.read(data_path('trc.fits'))
        trc = tbl['trc'].data
        # Call
        peaks, sigmas, ledges, redges = arutils.find_nminima(-1*trc, nsmooth=3)
        np.testing.assert_allclose(peaks, np.array([  4.86511462e+01,  -4.530896e-03,   7.17466301e+01,
             1.67786437e+02,   1.35216283e+02,   1.88809673e+02,
>            2.13649812e+02,   2.62738738e+02]), rtol=1e-5)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-05, atol=0
E       
E       (mismatch 12.5%)
E        x: array([  4.865115e+01,  -4.531052e-03,   7.174663e+01,   1.677864e+02,
E                1.352163e+02,   1.888097e+02,   2.136498e+02,   2.627387e+02])
E        y: array([  4.865115e+01,  -4.530896e-03,   7.174663e+01,   1.677864e+02,
E                1.352163e+02,   1.888097e+02,   2.136498e+02,   2.627387e+02])

pypit/tests/test_objfind.py:72: AssertionError
```

I'm on python 3.6 on OS El Capitan. After I updated arclines I did a `python setup.py install` and for PYPIT `python setup.py develop`.  I'm running  the unit tests with` python setup.py test`.

**Comment by rcooke-ast** [comment]
I feel like this might have been an issue that was fixed by @profxj recently. See PR #274. Does the previous result work better?

**Comment by AlexaVillaume** [comment]
I'm not sure I follow you. PR #274 was merged onto master, if the unit test failures were addressed in that PR wouldn't they be fixed?

>  Does the previous result work better?

Do you mean the previous version before the latest updates?

**Comment by rcooke-ast** [comment]
Sorry for my confusing reply. I just meant to say that this was the last time it was changed. For some reason, it passes travis on the other PRs but not on yours. I'm not entirely sure why. Have you tried pulling the master branch onto your computer, merging master to your branch, and then push the changes? Hopefully that will fix any issue. If not, it might be helpful to print the peaks array and run the tests (`python setup.py test`) to see how different peaks is from the expected value.

**Comment by profxj** [comment]
Most likely @AlexaVillaume has an older (maybe even a newer!)
version of Numpy or SciPy.

**Comment by AlexaVillaume** [comment]
> Most likely @AlexaVillaume has an older (maybe even a newer!)
version of Numpy or SciPy.

I'm using Numpy version 1.12.1 and Scipy version 0.19.0 on Pythn version 3.6.1. Are those too recent? Note that the installation documentation says Numpy version 1.10 or later and Scipy version 0.17 or later.

**Comment by profxj** [comment]
Looking at the Travis output on the master branch:
https://travis-ci.org/PYPIT/PYPIT/jobs/306751154

I see it is running Numpy 1.13 but I can't dig out which Scipy.

We should probably update the docs to say Numpy >= 1.12
or something like that..

But, bottom line, I think you are fine ignoring this test failure.

Closing

**Comment by AlexaVillaume** [comment]
I think I have to reopen this issue. I ignored this test failure as you suggested and I ran the test on the PYPIT development suite and I get 5/9 failures. Here's the the output from running `./pypit_test all` 

```
Running pypit on keck_hires_uv.pypit --- PASSED
[INFO]    :: Wrote: QA/HZ44_HIRES_2013May07T052156.621.html
[INFO]    :: Data reduction execution time: 6m 8.66s


Running pypit on keck_lris_blue_long_400_3400_d560.pypit --- FAILED
             ---> please contact the authors
[INFO]    :: Wrote: QA/MF_A.html


Running pypit on keck_lris_blue_long_600_4000_d560.pypit --- FAILED
             ---> please contact the authors
[INFO]    :: Wrote: QA/MF_A.html


Wrote ./keck_lris_red_2017-Nov-29.pypit
Wrote ./keck_lris_red_setup_A/keck_lris_red_setup_A.pypit
Finished running pypit on keck_lris_red_long_600_7500_d560 --- PASSED
[INFO]    :: Found 23 raw data frames
[INFO]    :: Input file loaded successfully


Running pypit on keck_lris_red_setup_A.pypit --- FAILED
             ---> please contact the authors
[INFO]    :: Wrote: QA/MF_A.html


Wrote ./shane_kast_blue_2017-Nov-29.pypit
Wrote ./shane_kast_blue_setup_A/shane_kast_blue_setup_A.pypit
Finished running pypit on shane_kast_blue_600_4310_d55 --- PASSED
[INFO]    :: Found 27 raw data frames
[INFO]    :: Input file loaded successfully


Running pypit on shane_kast_blue_setup_A.pypit --- FAILED
             ---> please contact the authors
[INFO]    :: Wrote: QA/MF_A.html


Running pypit on shane_kast_red_600_7500_d55.pypit --- FAILED
             ---> please contact the authors
[INFO]    :: Wrote: QA/MF_A.html


Running pypit on wht_isis_blue_long_r300b_d5300.pypit --- PASSED
[INFO]    :: Wrote: QA/MMT0155-0821_ISISb_2016Feb09T204740.546.html
[INFO]    :: Data reduction execution time: 8m 53.64s



--- PYPIT DEVELOPMENT SUITE FAILED 5/9 TESTS ---
```


I've double checked that my local PYPIT is up to date with the master branch and I updated numpy to be 1.13 (I still get the same unit test failure). I don't understand why if the master branch version works for others, it wouldn't work for me so I welcome any additional suggestions.

**Comment by rcooke-ast** [comment]
Have you also updated you `arclines` and `development suite` repos? You will also need to run `python setup.py develop` to reinstall PYPIT

**Comment by AlexaVillaume** [comment]
You were right @profxj -- the failures in the development suite were a red herring, they had nothing to do with the problems in the unit tests. It was because my conda environments were mixed up. All tests pass in the development suite. I'm excited to see how the updates to arclines go with my data!

**Comment by lwymarie** [comment]
@AlexaVillaume I'm curious about how you passed the unittest and the development test suite in the end. I have the exact same problems.

**Comment by AlexaVillaume** [comment]
@lwymarie I think in the end I just ignored the test failures, the reductions seem to be running fine.

**Comment by rcooke-ast** [comment]
@lwymarie: have you updated and installed the arclines package, and the development suite? You'll also need to reinstall PYPIT (i.e. don't just check out the latest master branch, you'll need to install the code too). Apart from that, try updating the dependencies. Are you using python 2 or 3?

**Comment by lwymarie** [comment]
All tests in the development test suite have passed after I reinstalled arclines and pypit. The pypit unittest still fails with rtol = 1e-5. But I trust X that it's okay.

**Comment by rcooke-ast** [comment]
Glad to hear it - thanks for the update!  I suspect the rtol issue is fine, too  :-)
