### ISSUE TITLE
airtovac

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#292]
Does anyone recall where the airtovac formula
we have in PYPIT came from?

@tiffanyhsyu ?

**Comment by profxj** [comment]
Is it the Ciddor equation as detailed here?

http://emtoolbox.nist.gov/Wavelength/Documentation.asp

**Comment by bomilvangjensen** [comment]
To me, airtovac() in arwave.py looks like https://idlastro.gsfc.nasa.gov/ftp/pro/astro/airtovac.pro which cites Ciddor 1996, Applied Optics 62, 958

**Comment by tiffanyhsyu** [comment]
Yup, I followed what’s given at https://idlastro.gsfc.nasa.gov/ftp/pro/astro/airtovac.pro

**Comment by profxj** [comment]
Documented in PR #303
