### ISSUE TITLE
Huge spikes in sensitivity function 

### ISSUE THREAD

**Issue by lwymarie** [PYPIT/PYPIT#294]
Attached a spectrum of BD+33 fluxed the sensitivity function generated by itself. After consulting @tiffanyhsyu , I extended the wavelength range for masking telluric absorption in arflux,py. Such that, it encompasses the spike at ~7200 angstroms. That didn't remove the spike. 

Tried changing the reduce skysub everyn parameter. Didn't help. 

<img width="1232" alt="bd 33" src="https://user-images.githubusercontent.com/20585911/35894454-945eeafc-0b67-11e8-9648-63b4174df5c1.png">

**Comment by rcooke-ast** [comment]
What does the counts spectrum look like (i.e. without applying the sensitivity function)? What does the sensitivity function look like? Are there any cosmic rays on the 2D frame that fall on the standard star?

**Comment by lwymarie** [comment]
Sorry for the confusion. The above is actually counts. I attached screenshots of counts versus flux comparison, a processed 2D spectrum, and a sky-subtracted 2D spectrum. I'm not good at judging whether the cosmic rays are significant.
![bd 33_counts_n_flux](https://user-images.githubusercontent.com/20585911/35935505-8ece8bcc-0bf5-11e8-8f11-df96d631179a.png)
![bd 33_processed](https://user-images.githubusercontent.com/20585911/35935511-925ba32e-0bf5-11e8-971c-037e29be1253.jpeg)
![bd 33_skysub](https://user-images.githubusercontent.com/20585911/35935518-95739756-0bf5-11e8-8615-1e67401c55ad.jpeg)

 I put the spectra in the Dropbox folder: 
https://www.dropbox.com/sh/fom31dofcnt4tc5/AACcpc6EbZPrOztg3yNyzCzja?dl=0
Would much appreciate help from @rcooke-ast or other developers!

**Comment by rcooke-ast** [comment]
See that ugly white dot near the position (150, 2065) on the 2D frame? That's responsible for the spike in the standard star spectrum. There seem to be a tonne of them littering the chip (even away from the slit), so it's probably a detector defect. I doubt it's a cosmic ray. @profxj any thoughts what this artefact might be?

**Comment by profxj** [comment]
Probably a chip defect.  Check your flat field image.
You might need to add it to the bpix image.

Is this kast red?

**Comment by profxj** [comment]
And of course there are plenty of CRs in the image too.
But I presume most of these are being dealt with..

**Comment by rcooke-ast** [comment]
Seems it (regarding the CR). There's a CR that hits the wing of the profile towards the bottom of the 2D frame, and this doesn't show up in the extracted spectrum - first thing I checked...

**Comment by lwymarie** [comment]
Wavelength runs from top to bottom, hence (150, 2065) is not close to the huge spike at ~7200 angstroms in the counts spectrum.  
The white dot at (150, 2065) does not correspond to any feature in a flat field image. I just put a flat field image in the Dropbox folder link. The dot is also distinct from the object trace. 
Can PYPIT co-add standard spectra if I take more of them, for cosmic ray rejection?
PS There's a big chip defect around pixel number (175, 2407), which resulted in a narrower object profile in appearance.

**Comment by bpholden** [comment]
Kast Red is a thick device, so it will have a lot of cosmic rays in an even
short exposure.
On top of that, there are alpha particles (those round dots) that come from
the dewar window. We will fix that soon, the new window is made but it
needs to be coated and installed.
I would suggest always taking two exposures and at least comparing the
pixels between them to make sure that the CRs are not causing an issue. I
understand that for standards this is a bit unusual.

**Comment by rcooke-ast** [comment]
@lwymarie, I'm pretty sure it's what I said (an alpha particle, according to @bpholden). I did a projection in DS9 - try this to confirm to yourself that the big dot lines up exactly with the feature in the spectrum.

**Comment by rcooke-ast** [comment]
In any case, I don't think there is a utility in PYPIT to deal with this at present. You're right though, you would need to combine several frames to remove the artefacts. Perhaps you can manually combine several 2D standard star frames before feeding these into PYPIT? You could simply update the data of one frame using astropy's fits module. In this case, you would probably need to calculate the median of ~3 standard star frames. Make sure you don't generate a new fits file (with an empty header), because the header contents needs to match at least one of the real standard star frames.

Also, just a reminder, it's probably best to make a copy of your raw standard star frames before trying any of this, in case something breaks  :-)

**Comment by rcooke-ast** [comment]
Alternatively, remove the offending standard star frame, and try another one... that's probably the easiest (and quickest... and less prone to error) option.
