### ISSUE TITLE
Combination of echelle orders

### ISSUE THREAD

**Issue by ntejos** [PYPIT/PYPIT#304]
Hi PYPYT developers,

Just a quick question. Is there a preferred implemented routine for combining echelle orders at the 1-D level?, i.e. calibrated spectra with variable S/N as a function of wavelength. Thanks.

Nicolas.

**Comment by rcooke-ast** [comment]
There's currently no algorithm in PYPIT to combine echelle orders (or multiple exposures, for that matter). The plan is to have an automated routine that will do this in PYPIT. The output files will also be in a format that can be read into [UVES_popler](https://github.com/MTMurphy77/UVES_popler), which I use religiously. It is a little bit laborious, but the end result is very good quality, probably the best I've come across. Note that some modification to UVES_popler will be needed for it to read in PYPIT files correctly. I've done this in a branch of mine, but I haven't submitted a PR for UVES_popler yet.

Also note that @tiffanyhsyu wrote an algorithm for combining multiple long slit exposures, which will essentially be the same thing as the echelle order combination. Check [this](https://github.com/PYPIT/PYPIT/blob/master/doc/coadding.rst) out. So, perhaps you can use that algorithm if you're looking for something relatively quick?
