### ISSUE TITLE
Moving msgs to pypit/__init__.py

### ISSUE THREAD

**Issue by kbwestfall** [PYPIT/PYPIT#308]
X and I talked about restructuring the front end of pypit to make it more clear and to hopefully remove some of the difficulties with the global objects.

First, I'm going to start a branch that will move the creation of the logger into the pypit/__init__.py file so that it's immediately available within the package.  A main goal is to hopefully remove the requirement on the order in which the logger and other modules are imported.  One subtlety it to make sure that the log file is correctly defined at the relevant locations.

The effect of this will touch many files, but I'm aiming that the only visible difference will be that:

```
from pypit import armsgs
msgs = armsgs.get_logger()
```

should just become:

```
from pypit import msgs
```

For an example, see here:

https://github.com/sdss/marvin/blob/master/python/marvin/__init__.py

Because `log` is defined at line 45, it's immediately available in the package by just saying:

```
from marvin import log
```

I'm hoping that something similar can be done with `settings`.  But first things first ...

**Comment by rcooke-ast** [comment]
This all sounds like a good idea to me! I tried to think of ways to do something similar, but this is very simple and clean - I like it  👍

**Comment by kbwestfall** [comment]
I actually finished getting this working this morning.  All the tests in the dev suite are passed.  I'll submit a PR once my other one gets approved :)

**Comment by rcooke-ast** [comment]
Great - I'll check out the PR on Monday - thanks!!

**Comment by kbwestfall** [comment]
Closing this.  See PR #310 .
