### ISSUE TITLE
merge ardebug.py and ginga.py

### ISSUE THREAD

**Issue by kbwestfall** [PYPIT/PYPIT#311]
Is there any reason to keep these as separate modules?

**Comment by profxj** [comment]
well, some of the methods in ginga are called by other
routines (e.g. pypit_show_2dspec).  Best to keep separate, I think.

**Comment by kbwestfall** [comment]
Sorry, I actually didn't really know what 'ginga' was.  I just assumed it was some debugging package, but I just searched it now and found out it's a visualization package.  I understand why they're different now.

Risking pedantry here, but there are a couple conceptual things about these two files that still bother me: (1) I worry about naming a module after the outside package it uses.  I think we want to name the modules by their purpose or by the general category of the methods they provide.  So I would rename ginga.py to something like visualize.py. (2) I also worry about importing methods within ardebug just so that they can be called as a part of ardebug later on (like the ginga and pdb imports).  I think it hurts the clarity of the code.
