### ISSUE TITLE
Trace objb image

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#312]
@rcooke-ast -- Is it possible to speed this algorithm up
greatly for ARMLSD:  artrace.trace_objbg_image()  ?

It is *very* slow for long slit, especially if many (>10)
objects are detected.  And I don't think the level of 
accuracy being achieved here is needed for low-dispersion work.

Thoughts?

**Comment by rcooke-ast** [comment]
Yes, I'm pretty sure I can code something quicker (albeit, slightly less accurate) up. Maybe save the current code for echelle work, though.

**Comment by profxj** [comment]
Sounds perfect.

**Comment by rcooke-ast** [comment]
Addressed by PR #320
