### ISSUE TITLE
apply_sensfunc should not operate on accessible quantities, not on slf. 

### ISSUE THREAD

**Issue by jhennawi** [PYPIT/PYPIT#332]
As the code is currently written there is no way to flux calibrate data after the main pipeline has run. This has major disadvantages in my opinion. 

The user should be able to flux calibrate a spectrum with a script after the pipeline has run, for example to incorporate a standard star from another nights reduction or whatever. I'm fine with fluxing being part of the main pipeline, but in the current way that apply_sensfunc is written, it cannot be easily run outside of PYPIT on outputs from PYPIT. 

This problem can easily be remedied if you just strip out the object oriented fanciness from apply_sensfunc (which in this case serves no purpose, and makes the code less flexible) and simply allow it to take arguments specobjs, sensfunc, etc.

**Comment by profxj** [comment]
I've started a branch that will address this  'flux_spec'.

Just a head's up.

**Comment by profxj** [comment]
Addressed by PR #341
