### ISSUE TITLE
Turn off Cython?

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#337]
@kbwestfall -- Are we ready to remove Cython as a dependency?

At least for non-developers?

**Comment by kbwestfall** [comment]
I have no problem with doing this.  How far do we want to go?  We can just move the cython files into a directory to keep the code around, and comment out any use of it.  Or we can explicitly remove it all, and bank on the revision history if we need to get it back for some reason.

**Comment by kbwestfall** [comment]
Addressed in #376.
