### ISSUE TITLE
xdb vs pdb

### ISSUE THREAD

**Issue by rcooke-ast** [PYPIT/PYPIT#34]
I propose that throughout the code we use following debug import statement:

try:
    from xastropy.xutils import xdebug as xdb
except:
   import pdb as xdb

It would save us the trouble of changing xdb to pdb inline (and vice versa), especially if someone does not have xastropy installed. Then, throughout the code we consistently use: xdb.set_trace()

Any objections to me implementing this in my coming PR?

**Comment by rcooke-ast** [comment]
Alternatively, we could do:

try:
from xastropy.xutils.xdebug import set_trace
except:
from pdb import set_trace

and throughout remove the namespace, and instead just use:
set_trace()

X, does this import line work for your xdebug?

**Comment by profxj** [comment]
I believe it does indeed.

Cheers,

X

> On Mar 27, 2016, at 8:29 AM, Ryan Cooke <notifications@github.com> wrote:
> 
> Alternatively, we could do:
> 
> try:
> from xastropy.xutils.xdebug import set_trace
> except:
> from pdb import set_trace
> 
> and throughout remove the namespace, and instead just use:
> set_trace()
> 
> X, does this import line work for your xdebug?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/PYPIT/PYPIT/issues/34#issuecomment-202089460>
> !DSPAM:826,56f7fc5c1277110476546!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by profxj** [comment]
This would be fine too.

X

> On Mar 27, 2016, at 8:22 AM, Ryan Cooke <notifications@github.com> wrote:
> 
> I propose that throughout the code we use following debug import statement:
> 
> try:
> from xastropy.xutils import xdebug as xdb
> except:
> import pdb as xdb
> 
> It would save us the trouble of changing xdb to pdb inline (and vice versa), especially if someone does not have xastropy installed. Then, throughout the code we consistently use: xdb.set_trace()
> 
> Any objections to me implementing this in my coming PR?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/PYPIT/PYPIT/issues/34>
> !DSPAM:826,56f7fac8126292456925429!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)
