### ISSUE TITLE
Let's discuss the philosophy of the Scienceimage class

### ISSUE THREAD

**Issue by jhennawi** [PYPIT/PYPIT#350]
https://github.com/PYPIT/PYPIT/blob/f160bdddc799822bb2a0e2ff3dfacd99ae05061b/pypit/arms.py#L290

I'm willing to live with it, but there should not be 20 lines of code associated with it. 

In my opinion, we I just need to read in an image and proc it with the bias and flats, create a cr mask etc. All of this should be done by the same code that reads in the images (arproc?). It should return a sciimg, sciivar, and a read noise image. 

Joe

**Comment by profxj** [comment]
There is more than that, of course.

And I think it should also include the call to the  global sky sub method as that mainly uses these images.

Have put object finding and extraction in there for now, but as they generate or modify other objects it will probably be better to do them outside the class.  Just didn't have a framework for those yet.

**Comment by profxj** [comment]
I propose we keep the object finding and extraction in here
until we bring in the new algorithms for each of these.

**Comment by profxj** [comment]
Closing
