### ISSUE TITLE
when will we not need to sky sub?

### ISSUE THREAD

**Issue by jhennawi** [PYPIT/PYPIT#351]
https://github.com/PYPIT/PYPIT/blob/f160bdddc799822bb2a0e2ff3dfacd99ae05061b/pypit/arms.py#L315

I'm not following this really since I think we will always need to sky-subtract. But maybe you enlighten me on the cases where we don't need to. Don't say near-IR reductions diff image reductions, because that is incorrect. 

Joe

**Comment by rcooke-ast** [comment]
This is probably something copied over from ARMED.

Short slits and bright objects. I’ve previously observed a bunch of Milky Way OB stars with echelle, where you don’t want to sky subtract.

I presume this may happen (rarely) with multislit data, but presumably you would want to determine this on a slit by slit case... maybe when the object profile is significantly non zero at the slit edges.

**Comment by profxj** [comment]
Agreed
