### ISSUE TITLE
Raw variance 'floor'

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#354]
Pasting in a thread that was in PR #353 

This should be its own PR once it is resolved.

==
rcooke-ast a day ago  Member
This doesn't make sense to me. what is the factor - np.sqrt(2)*np.sqrt(rnoise) doing? I know that this is present in HIRESredux, but I didn't really understand it there either. I think it would be good to add a comment why this is needed.

  @profxj
profxj a day ago  Member
It is needed in the regime when there are very few counts.
It is not a precise estimate, but was a recipe we settled on
after some experimentation. Perhaps @jhennawi can recall
better the origin of this actual implementation.

  @jhennawi
jhennawi 21 hours ago  Collaborator
This is a hack to give approximately the correct variance in the low count limit where the gaussian approximation fails.

  @rcooke-ast
rcooke-ast 20 hours ago  Member
Seems like we’re just shifting the zero point to be centred on sqrt(2*rnoise). I would think that a better approach might be to clip sciframe to have no values less than 1, and avoid taking the absolute value.

I appreciate that the implementation used in IDL has been well-tested, but it does seem a little arbitrary...

  @jhennawi
jhennawi 19 hours ago  Collaborator
Everything we do in this reduction pipeline assumes variances add in quadrature. That won't be the case for Poissonian noise. That means extracted noise will be wrong and weights will be wrong if you are truly in the Poisson limit. This kludge of the inverse variance basically gives you approximately the variance of the Poisson distribution, which is probably the best thing you can do. It is also basically setting a floor on the inverse variance so that you don't give infinite weight to low-count pixels, and instead give them uniform weights.

  @rcooke-ast
rcooke-ast 16 hours ago  Member
OK - thanks for the explanation - we should include this statement (or something like this) in a comment in the code, saying explicitly that the factor BLAH is a kludge. However, it still doesn't seem right to me... what happens in the case where rnoise=2? If you have sciframe = 2, then this term goes to zero and you're left with varframe=rnoise + dnoise. Note, this is also in the Poisson regime of low counts. So, unless I'm missing something, we should include an explanation in the code and/or a reference to where/how this kludge factor was determined (was it instrument specific?).

I guess I'm just pointing out that, I agree that np.abs(scicopy) + rnoise + dnoise is probably not the whole story, but the newly proposed equation is no better. So, we either need to justify one or the other, or come up with a new strategy.

**Comment by rcooke-ast** [comment]
I had a look for other examples of this, to see how it's dealt with, and I came up essentially empty handed. There are a few COS papers that discuss deviations from Poisson statistics at low S/N...

If there's some confidence in the proposed implementation (the same used for the old IDL routines), then I'm cautiously willing to go with it, but we should state why we are using a non-standard fudge factor when calculating the variance, and where this came from originally.

Perhaps we should eventually deal with this properly (which probably won't involve calculating a simple variance image). Instead, we could calculate a flux probability distribution for each pixel, but I think this would require a lot more thought... No doubt, it will look like the convolution of a Gaussian and Poisson distribution.

**Comment by profxj** [comment]
@jhennawi snuck this in with a 'not worse pursuing' in his 
first extraction PR.
