### ISSUE TITLE
Lots of confusing and defunct notebooks. Which ones do we need?

### ISSUE THREAD

**Issue by jhennawi** [PYPIT/PYPIT#357]
Hi All, 

I'm trying to figure out how to read in a image and run the new slit tracing algorithms. I understood @profxj had created a notebook for this. In trying to find it, I see lots of notebooks that don't appear to be necessary. My suggestion is that we move the defunct or unnecessary notebooks to the dev suite, and only keep in doc/nb those notebooks that we expect non-developers to be consult and understand. 

To this end, it would be nice if we got into the habit of starting each notebook with a little pre-amble explaining what the notebook is for. 

Thanks!
Joe

**Comment by profxj** [comment]
I have the same reaction to this Issue as #358.  Each of these new
Notebooks was called out in its PR.  Would be hard to not have seen
where they are.

The docs need *a lot* of work.  But that is a much bigger issue than a
few Notebooks.
