### ISSUE TITLE
The Difference Between “is” and “==” in Python

### ISSUE THREAD

**Issue by jhennawi** [PYPIT/PYPIT#379]
Dear @profxj , 

Plseae carefully read this article before you change my == False to is False: 

https://dbader.org/blog/difference-between-is-and-equals-in-python

My version of bspline_profile: 

qdone = False
tempin = None
while (error != 0 or qdone == False) and iiter <= maxiter:

Your "fix" which completely broke the sky subtraction and prevented it from iterating:)

qdone = False
tempin = None
while (error != 0 or qdone is False) and iiter <= maxiter:

I avoid is at all costs for this reason, unless I've set something to None and do an is None. 

Anyway, perhaps this was a bug in djs_reject and how qdone is set to false, but I doubt it. 

Joe

**Comment by profxj** [comment]
I love it when you yell at me and then retract all before I wake up.
