### ISSUE TITLE
Change the input filename extension?

### ISSUE THREAD

**Issue by rcooke-ast** [PYPIT/PYPIT#38]
At the moment only a ".red" file is allowed to be read in. But this might be a confusing extension if there's a red and a blue arm of the instrument, and red/blue is in the filename.

Please propose your favourite alternatives! Here are some suggestions:

.reduce
.pypit
.input
.in

I quite like ".pypit", but I'm not married to it...

**Comment by profxj** [comment]
Let's use PYPIT
