### ISSUE TITLE
Avoiding multiple instances of Spectrograph

### ISSUE THREAD

**Issue by kbwestfall** [PYPIT/PYPIT#389]
After digging in, I realized that if we only ever pass a string (or header) definition of the spectrograph to ProcessImages (or it's children), each of those instances will have it's own independent instance of Spectrograph.  We want to avoid this.

The way I will do that for the moment is to have Calibrations be the uber class that holds that actual, single instance of Spectrograph.  ProcessImages will maintain its ability to create a Spectrograph instance if it needs to, but, when instantiated from within Calibrations, it will only point to that single instance.

**Comment by profxj** [comment]
@jhennawi -- Your input is needed here.  Especially if we are going to
address this in v0.8

**Comment by profxj** [comment]
Pinging @jhennawi

**Comment by profxj** [comment]
Discussed.
