### ISSUE TITLE
Intra-package imports?

### ISSUE THREAD

**Issue by kbwestfall** [PYPIT/PYPIT#404]
Any preference for or against [intra-package references](https://docs.python.org/3/tutorial/modules.html#intra-package-references)?

I.e. in traceimage.py do you prefer:
```
import inspect
import numpy as np

from pypit import msgs
from pypit import processimages
from pypit.par import pypitpar

from pypit import ardebug as debugger
```
or
```
import inspect
import numpy as np

from . import msgs
from . import processimages
from .par import pypitpar

from . import ardebug as debugger
```

I've started to mix them, but we should probably pick a convention and stick to it.

**Comment by jhennawi** [comment]
I prefer the former maximally explicit model.  A related question I have is whether we should be doing

from scipy.interpolate import medfilt

Or whether I should be writing 

import spicy

yy = scipy.interpolate.medfilt(XX) 

Joe

**Comment by kbwestfall** [comment]
Okay, sounds good.  I'll leave this open for now as a reminder to change the imports before merging #400.

I think technically doing `from scipy.interpolate import medfilt` is the same as saying `import scipy.interpolate.medfilt as medfilt`.  So even though I have a (possibly irrational) dislike of using `as`, I don't have any problem using `from`.

As for `from scipy.interpolate import medfilt` vs. `from scipy import interpolate`, I tend to do the former if I only ever need `medfilt` within the given module and do the latter when I need multiple functions from `interpolate`.

**Comment by kbwestfall** [comment]
All imports now follow the first mode as of #400.  Closing.
