### ISSUE TITLE
arflags output

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#53]
We should write the arflags as a JSON file (or YAML)
as part of the standard outputs.  This would really save
the input parameters (i.e. including the defaults).

**Comment by rcooke-ast** [comment]
Agreed. But, it might be better to save the argflags in the same format as they are input. Then, we should also add a keyword argument to allow these to be input into a user's .red input file, something like:

```
run argflag filename.argflag
run instargflag filename.instargflag
```

**Comment by rcooke-ast** [comment]
I've done this, but will send the PR when I'm finished the new parser

**Comment by rcooke-ast** [comment]
Now implemented in the parser branch
