### ISSUE TITLE
wtilt nan's in artrace

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#55]
There are NAN's entering in the calculation of wtilt
in artrace.py at line 1087:

            if wmask.size != 0:
                wtilt[xint:xint+2*sz+1, j] = np.sqrt(2.0) / (1.4826 * np.median(np.abs(ytfit-model)[wmask]))

This leads to NANs for the tilts.
Not sure why, nor how to mitigate.

This is occurring in the Kast blue test suite.

**Comment by rcooke-ast** [comment]
Hmm... I haven't been able to reproduce this (with either KastB or LRISB), using spca, spline or interp methods. Can you confirm that you have the latest version of the code, and that your cython files are compiled to reflect the latest versions? Failing this, please place all files in the PYPIT Dropbox and I'll try to reproduce it from there.  Thanks!

**Comment by profxj** [comment]
Sorry, I hadn't recompiled Cython.
Closing.
