### ISSUE TITLE
Local sky sub + CRs

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#61]
Unidentified CRs are causing poor results in local 
sky subtraction:

https://www.dropbox.com/s/hujnvi0quvy0icb/Screenshot%202016-05-02%2005.34.51.png?dl=0

Consider adding a clipping step to arcyutils.func2d_fit_val

**Comment by rcooke-ast** [comment]
That isn't good... seems strange that only two rows were affected, given that the CRs spanned many rows... Seems to suggest (to me) that we might need to change/replace the L.A. Cosmics algorithm.

**Comment by profxj** [comment]
Addressed in PR #183
