### ISSUE TITLE
Mac OSX El Capitan issues

### ISSUE THREAD

**Issue by cleibler** [PYPIT/PYPIT#93]
Hey Ryan,
GSL, if installed by anaconda, causes issues in the test suite due to some relative paths (@rpath) that appear in .so files. This is an issue with the El Capitan operating system in particular (which introduced system integrity protection). 
If you were able to change those relative paths to full paths (every installer should have defined the GSL_PATH and LD_LIBRARY_PATH environment variables in their rc files (see the new installation documentation I added), this issue would go away and people who installed GSL with anaconda could avoid some ugly hacks. 

Thanks!
Camille

**Comment by profxj** [comment]
Am assuming we are past this.
